// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jklhcltnsghncibkeafs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbGhjbHRuc2dobmNpYmtlYWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjU0MTMsImV4cCI6MjA2MDY0MTQxM30.xWMSVQSBKJ7vCbsZXZ37xTG_HqQGvjLdIR0-iJ9sP4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);